### ISSUE TITLE
expecting "autocomplete_result_select" handler in Menu component

### ISSUE THREAD

**Issue by endoooo** [camino-school/lanttern#16]
in some cases, when selecting a curriculum item in create or update assessment point overlay, an error message is flashed.

(need further investigation to understand what is the exactly case, because it does not happen every time).

error message:

```
[error] GenServer #PID<0.1321.0> terminating
** (FunctionClauseError) no function clause matching in LantternWeb.MenuComponent.handle_event/3
    (lanttern 0.1.0) lib/lanttern_web/live_components/menu_component.ex:249: LantternWeb.MenuComponent.handle_event("autocomplete_result_select", %{"id" => "1", "name" => "English LO 1"}, #Phoenix.LiveView.Socket<id: "phx-F46a7Klwshs7kgWB", endpoint: LantternWeb.Endpoint, view: LantternWeb.AssessmentPointLive, parent_pid: nil, root_pid: #PID<0.1321.0>, router: LantternWeb.Router, assigns: %{id: "menu", profile_name: "The Teacher", profiles: [%Lanttern.Identity.Profile{__meta__: #Ecto.Schema.Metadata<:loaded, "profiles">, id: 1, type: "teacher", user_id: 1, user: #Ecto.Association.NotLoaded<association :user is not loaded>, student_id: nil, student: nil, teacher_id: 1, teacher: %Lanttern.Schools.Teacher{__meta__: #Ecto.Schema.Metadata<:loaded, "teachers">, id: 1, name: "The Teacher", school_id: 1, school: %Lanttern.Schools.School{__meta__: #Ecto.Schema.Metadata<:loaded, "schools">, id: 1, name: "The School", inserted_at: ~N[2023-10-16 13:49:58], updated_at: ~N[2023-10-16 13:49:58]}, inserted_at: ~N[2023-10-16 13:49:58], updated_at: ~N[2023-10-16 13:49:58]}, inserted_at: ~N[2023-10-16 13:49:59], updated_at: ~N[2023-10-16 13:49:59]}], __changed__: %{}, current_user: #Lanttern.Identity.User<__meta__: #Ecto.Schema.Metadata<:loaded, "users">, id: 1, email: "eric.endo@caminoschool.com.br", is_root_admin: true, confirmed_at: nil, current_profile_id: 1, current_profile: %Lanttern.Identity.Profile{__meta__: #Ecto.Schema.Metadata<:loaded, "profiles">, id: 1, type: "teacher", user_id: 1, user: #Ecto.Association.NotLoaded<association :user is not loaded>, student_id: nil, student: nil, teacher_id: 1, teacher: %Lanttern.Schools.Teacher{__meta__: #Ecto.Schema.Metadata<:loaded, "teachers">, id: 1, name: "The Teacher", school_id: 1, school: %Lanttern.Schools.School{__meta__: #Ecto.Schema.Metadata<:loaded, "schools">, id: 1, name: "The School", inserted_at: ~N[2023-10-16 13:49:58], updated_at: ~N[2023-10-16 13:49:58]}, inserted_at: ~N[2023-10-16 13:49:58], updated_at: ~N[2023-10-16 13:49:58]}, inserted_at: ~N[2023-10-16 13:49:59], updated_at: ~N[2023-10-16 13:49:59]}, inserted_at: ~N[2023-10-16 13:49:59], updated_at: ~N[2023-10-16 13:50:12], ...>, flash: %{}, current_path: "/assessment_points/1", myself: %Phoenix.LiveComponent.CID{cid: 7}, active_nav: :assessment_points, profile_type: "Teacher", profile_school: "The School"}, transport_pid: #PID<0.1253.0>, ...>)
    (phoenix_live_view 0.20.0) lib/phoenix_live_view/channel.ex:716: anonymous fn/4 in Phoenix.LiveView.Channel.inner_component_handle_event/4
    (telemetry 1.2.1) /Users/endo/camino-school/dev/lanttern/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
    (phoenix_live_view 0.20.0) lib/phoenix_live_view/diff.ex:204: Phoenix.LiveView.Diff.write_component/4
    (phoenix_live_view 0.20.0) lib/phoenix_live_view/channel.ex:639: Phoenix.LiveView.Channel.component_handle_event/6
    (stdlib 5.0.2) gen_server.erl:1077: :gen_server.try_handle_info/3
    (stdlib 5.0.2) gen_server.erl:1165: :gen_server.handle_msg/6
    (stdlib 5.0.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
Last message: %Phoenix.Socket.Message{topic: "lv:phx-F46a7Klwshs7kgWB", event: "event", payload: %{"cid" => 7, "event" => "autocomplete_result_select", "type" => "hook", "value" => %{"id" => "1", "name" => "English LO 1"}}, ref: "29", join_ref: "26"}
State: %{socket: #Phoenix.LiveView.Socket<id: "phx-F46a7Klwshs7kgWB", endpoint: LantternWeb.Endpoint, view: LantternWeb.AssessmentPointLive, parent_pid: nil, root_pid: #PID<0.1321.0>, router: LantternWeb.Router, assigns: %{__changed__: %{}, current_user: #Lanttern.Identity.User<__meta__: #Ecto.Schema.Metadata<:loaded, "users">, id: 1, email: "eric.endo@caminoschool.com.br", is_root_admin: true, confirmed_at: nil, current_profile_id: 1, current_profile: %Lanttern.Identity.Profile{__meta__: #Ecto.Schema.Metadata<:loaded, "profiles">, id: 1, type: "teacher", user_id: 1, user: #Ecto.Association.NotLoaded<association :user is not loaded>, student_id: nil, student: nil, teacher_id: 1, teacher: %Lanttern.Schools.Teacher{__meta__: #Ecto.Schema.Metadata<:loaded, "teachers">, id: 1, name: "The Teacher", school_id: 1, school: %Lanttern.Schools.School{__meta__: #Ecto.Schema.Metadata<:loaded, "schools">, id: 1, name: "The School", inserted_at: ~N[2023-10-16 13:49:58], updated_at: ~N[2023-10-16 13:49:58]}, inserted_at: ~N[2023-10-16 13:49:58], updated_at: ~N[2023-10-16 13:49:58]}, inserted_at: ~N[2023-10-16 13:49:59], updated_at: ~N[2023-10-16 13:49:59]}, inserted_at: ~N[2023-10-16 13:49:59], updated_at: ~N[2023-10-16 13:50:12], ...>, flash: %{}, ordinal_values: [%Lanttern.Grading.OrdinalValue{__meta__: #Ecto.Schema.Metadata<:loaded, "ordinal_values">, id: 6, name: "Lack of evidence", normalized_value: 0.0, bg_color: "#2D0808", text_color: "#FFFFFF", scale_id: 2, scale: #Ecto.Association.NotLoaded<association :scale is not loaded>, inserted_at: ~N[2023-10-16 13:49:59], updated_at: ~N[2023-10-16 13:49:59]}, %Lanttern.Grading.OrdinalValue{__meta__: #Ecto.Schema.Metadata<:loaded, "ordinal_values">, id: 7, name: "Emerging", normalized_value: 0.4, bg_color: "#F28888", text_color: "#F6DFDF", scale_id: 2, scale: #Ecto.Association.NotLoaded<association :scale is not loaded>, inserted_at: ~N[2023-10-16 13:49:59], updated_at: ~N[2023-10-16 13:49:59]}, %Lanttern.Grading.OrdinalValue{__meta__: #Ecto.Schema.Metadata<:loaded, "ordinal_values">, id: 8, name: "Progressing", normalized_value: 0.6, bg_color: "#FFF48F", text_color: "#756A07", scale_id: 2, scale: #Ecto.Association.NotLoaded<association :scale is not loaded>, inserted_at: ~N[2023-10-16 13:49:59], updated_at: ~N[2023-10-16 13:49:59]}, %Lanttern.Grading.OrdinalValue{__meta__: #Ecto.Schema.Metadata<:loaded, "ordinal_values">, id: 9, name: "Achieving", normalized_value: 0.85, bg_color: "#5CD9BB", text_color: "#133F34", scale_id: 2, scale: #Ecto.Association.NotLoaded<association :scale is not loaded>, inserted_at: ~N[2023-10-16 13:49:59], updated_at: ~N[2023-10-16 13:49:59]}, %Lanttern.Grading.OrdinalValue{__meta__: #Ecto.Schema.Metadata<:loaded, "ordinal_values">, id: 10, name: "Exceeding", normalized_value: 1.0, bg_color: "#814BF4", text_color: "#D9C8FC", scale_id: 2, scale: #Ecto.Association.NotLoaded<association :scale is not loaded>, inserted_at: ~N[2023-10-16 13:49:59], updated_at: ~N[2023-10-16 13:49:59]}], assessment_point: %Lanttern.Assessments.AssessmentPoint{__meta__: #Ecto.Schema.Metadata<:loaded, "assessment_points">, id: 1, name: "English reading", datetime: ~U[2023-10-16 10:49:59Z], description: "Eius recusandae dolores voluptatem pariatur mollitia voluptatem vel porro.", date: nil, hour: nil, minute: nil, class_id: nil, classes_ids: nil, student_id: nil, students_ids: nil, curriculum_item_id: 1, curriculum_item: %Lanttern.Curricula.CurriculumItem{__meta__: #Ecto.Schema.Metadata<:loaded, "curriculum_items">, id: 1, name: "English LO 1", code: nil, subjects_ids: nil, years_ids: nil, grade_composition_component_items: #Ecto.Association.NotLoaded<association :grade_composition_component_items is not loaded>, assessment_points: #Ecto.Association.NotLoaded<association :assessment_points is not loaded>, curriculum_component_id: 1, curriculum_component: #Ecto.Association.NotLoaded<association :curriculum_component is not loaded>, subjects: #Ecto.Association.NotLoaded<association :subjects is not loaded>, years: #Ecto.Association.NotLoaded<association :years is not loaded>, inserted_at: ~N[2023-10-16 13:49:59], updated_at: ~N[2023-10-16 13:49:59], children_id: nil, component_code: nil}, scale_id: 2, scale: %Lanttern.Grading.Scale{__meta__: #Ecto.Schema.Metadata<:loaded, "grading_scales">, id: 2, name: "Camino Levels", type: "ordinal", start: nil, stop: nil, breakpoints: [0.2, 0.5, 0.7, 0.9], ordinal_values: #Ecto.Association.NotLoaded<association :ordinal_values is not loaded>, inserted_at: ~N[2023-10-16 13:49:59], updated_at: ~N[2023-10-16 13:49:59]}, entries: #Ecto.Association.NotLoaded<association :entries is not lo (truncated)
```

**Comment by endoooo** [comment]
when selecting a curriculum item one of the event listeners was being triggered many times because we were not removing the listeners — so, after some navigation between the assessment explorer and assessment details pages, we ended up with a lot of duplicated event listeners, which was causing this issue of the event kind of "leaking" to the menu component.
